import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Provider } from "@/providers/Providers";
import { ThemeContextProvider } from "@/context/ThemeContext";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Code Softwares",
  description: "Generated by Yasir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <ThemeContextProvider>
            <Navbar />
            {children}
            <Footer />
          </ThemeContextProvider>
        </Provider>
      </body>
    </html>
  );
}
